version: '3'
services:
  frontend:
    container_name: machi_viewer
    build:
      context: .
      dockerfile: ./deployment.d/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./deployment.d/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    hostname: machi-viewer
    networks:
      - machi_viewer_frontend
      - machi_viewer_backend
    restart: always

networks:
  machi_viewer_frontend:
  machi_viewer_backend:
    external: true
