version: '3'
services:
  database:
    container_name: pgsql
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DATABASE} 
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./database/sql_init:/docker-entrypoint-initdb.d